import NavBar from '@/components/NavBar';
import useAuthUser from '@/hooks/useAuthUser';
import style from "@/styles/App.module.css";
import '@/styles/globals.scss';
import "@/styles/utils.css";
import type { AppProps } from 'next/app';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useRouter } from 'next/router';
import NextNProgress from "nextjs-progressbar";
import { useEffect } from 'react';
import { Container } from "react-bootstrap";
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  useOnboarding();

  return (
    <>
      <Head>
        <title>Create Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <Toaster />
        <NextNProgress color='#F8C7CC' />
        <NavBar />
        <main>
          <Container className={style.pageContainer}>
            <Component {...pageProps} />
          </Container>
        </main>
      </div>
    </>

  )
}

function useOnboarding() {
  const { user } = useAuthUser();
  const router = useRouter();

  useEffect(() => {
    if (user && !user.username && router.pathname !== "/onboarding") {
      router.push("/onboarding?returnTo=" + router.asPath);
    }
  }, [user, router]);
}